dist: xenial

addons:
  postgresql: '10'

before_install:
  - sudo service postgresql stop
  - curl -sLO https://apt.postgresql.org/pub/repos/apt/pool/main/g/geos/libgeos-3.7.1_3.7.1-1~pgdg16.04%2b1_amd64.deb && sudo dpkg -i libgeos-3.7.1_3.7.1-1~pgdg16.04%2b1_amd64.deb
  - curl -sLO https://apt.postgresql.org/pub/repos/apt/pool/main/g/geos/libgeos-c1v5_3.7.1-1~pgdg16.04%2b1_amd64.deb && sudo dpkg -i libgeos-c1v5_3.7.1-1~pgdg16.04%2b1_amd64.deb
  - sudo apt install postgresql-10-postgis-2.5 postgresql-10-postgis-2.5-scripts
  - sudo service postgresql start 10

services:
  - postgresql

script:
  - psql --version
  - psql -c 'SELECT version()'
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -c 'CREATE EXTENSION IF NOT EXISTS postgis' -U postgres
  - psql -c 'SELECT PostGIS_full_version()' -U postgres
  - echo "Done"
